"use client"

import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { useState } from 'react';
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const [count, setCount] = useState(0);

  return (
    <html lang="en">
      <body className={inter.className}>
        <h2>Header</h2>
        <button onClick={() => setCount(count + 1)}>+</button>
        <h1>{count}</h1>
        <Link href="/page1">
          <span>Page1へ</span>
        </Link>
        <br />
        {children}
      </body>
    </html>
  )
}
